language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

script:
 - vendor/bin/phpunit

before_script:
 - composer install --no-interaction --prefer-source --dev

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  email:
    - me@mikevanriel.com
    - ashnazg@php.net
